### ISSUE TITLE
Tracking Issue for Tower Defense

### ISSUE THREAD

**Issue by LinearZoetrope** [SCAII/SCAII#112]
- [ ] Pass 1 
    - [ ] Unwrap map of info into hover box (#99, #100)
    - [ ] Straight path for one triangle
         - [ ] Issue unit orders from Lua (#101)
         - [ ]  Global/entity data store (#102, #110)
         - [ ]  Trigger volume for hitting agent (#103)
- [ ] Pass 2
    - [ ] Make path crooked w/ trigger volume and unit orders
    - [ ] Render landscapes or "decorative" objects (#104)
- [ ] Pass 3
    - [ ] Place agent towers
        - [ ] Allow Lua to interpret/translate actions ? (#105)
        - [ ] Fix Python state representation to allow arbitrary data (#106)
        - [ ] Allow agent to build/spawn units (#107)
- [ ] PASS 4 
    -  [ ] Add Multiple unit types including rock paper scissors
        - [ ] Unit armor/damage types (#108)
    - [ ] Timer trigger 
    - [ ] Allow agent to upgrade towers
        - May be easiest with #105
        - Should these be separate unit types, or an upgrade field?
        - May end up involving a version of #109 but with the glue side	
- [ ] PASS 5
	- [ ] Fix tower attack bug towers stop firing when unit leaves (#111) (may move earlier if needed)
