### ISSUE TITLE
Tracking issue for refactor and consolidation

### ISSUE THREAD

**Issue by LinearZoetrope** [SCAII/SCAII#73]
- [x] Merge RTS into dev, see the rts_stage branch for details
    - [x] Put it in `SCAII/backends/sky_rts`
    - [x] Move everything from `RTS/backend/*` to just the root level of `backends/sky_rts`
        - [x] Add to the workspace of `SCAII`
        - [x] Change the `scaii_defs` dependency in the RTS to a `path`-style one
    - [x] Change the target name from `backend` to `sky_rts`
    - [x] Deprecate `SCAII/Sky-RTS`
    - [x] Move RTS issues here 
- [x] Refactor directories for normalcy between RTS and core
    - [x] Rename `SCAII/common_protos` to `protos`
    - [x] Rename `game_wrapper` in RTS to `glue`
    - [x] Move `RTS/glue/python/*` into `RTS/glue/python/sky_rts/*`
- [x] Prime installer for changes (SCAII/Sky-install#9)

**Comment by LinearZoetrope** [comment]
I removed some of the cleanup stuff in favor of another issue to be handled after the demo.

**Comment by LinearZoetrope** [comment]
Issues culled and moved, #95, #96
